#include <iostream>

struct X {
  char member;
};
//can do a lot of operation even with this simple struct
int main() {
  X x1;                 // default ctor
  X x2{x1};             // copy ctor
  X x3{std::move(x2)};  // move ctor //stealing resources to x2
  //move is since c++11
  X x4{};               // default ctor calling {} to each member of the struct
  //calling default constructor with () is compile error
  //() are for calling functions
  x4 = x3;              // copy assignment 
  X x5;                 // default ctor
  x5 = std::move(x4);   // move assignment
  std::cout << x5.member << std::endl;  // what do you expect??
  //goign up and up we arrive to x1 that we didn't initialize
  //functions are generated by the compiler
  return 0;
}
